apiVersion: v1
kind: Secret
metadata:
  name: payment
  namespace: roboshop
type: Opaque
data:
  AMQP_USER: cm9ib3Nob3A=
  AMQP_PASS: cm9ib3Nob3AxMjM=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    app: payment
    tier: db

spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: payment
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        app: payment
        tier: db
    spec:
      containers:
      - name: payment
        image: satishsunkara/payment:v1
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: payment
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    project: roboshop
    app: payment
    tier: db
  ports:
  - protocol: TCP
    port: 5672 #service-port
    targetPort: 5672 #container-port