apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    app: cart
    tier: app

spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: cart
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        app: cart
        tier: app
    spec:
      containers:
      - name: cart
        image: satishsunkara/cart:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
    project: roboshop
    app: cart
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port