apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    app: shipping
    tier: app

spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: shipping
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        app: shipping
        tier: app
    spec:
      containers:
      - name: shipping
        image: satishsunkara/shipping:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    project: roboshop
    app: shipping
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port