apiVersion: app/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    app: mongodb
    tier: db

spec:
  replicas: 3
  selector:
    matchLabels:
      project: roboshop
      app: mongodb
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        app: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: satishsunkara//mongodb:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    demo: deployment
  ports:
  - protocol: TCP
    port: 27017 #service-port
    targetPort: 27017 #container-port