apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data:
  MONGO: "true"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    app: user
    tier: app

spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: user
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        app: user
        tier: app
    spec:
      containers:
      - name: user
        image: satishsunkara/user:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: user
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    project: roboshop
    app: user
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port