apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    app: redis
    tier: db

spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: redis  
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        app: redis    
        tier: db
    spec:
      containers:
      - name: redis  
        image: redis
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    project: roboshop
    app: redis
    tier: db
  ports:
  - protocol: TCP
    port: 6379 #service-port
    targetPort: 6379 #container-port